## The One-vs-Rest strategy(ovr) and One-vs-One(ovo)

Read this blog :

https://towardsdatascience.com/multi-class-classification-one-vs-all-one-vs-one-94daed32a87b

Not all classification predictive models support multi-class classification.

Algorithms such as the Perceptron, Logistic Regression, and Support Vector Machines were designed for binary classification and do not natively support classification tasks with more than two classes.

One approach for using binary classification algorithms for multi-classification problems is to split the multi-class classification dataset into multiple binary classification datasets and fit a binary classification model on each. Two different examples of this approach are the One-vs-Rest and One-vs-One strategies.

For more details refer below blog

https://machinelearningmastery.com/one-vs-rest-and-one-vs-one-for-multi-class-classification/


**The One-vs-Rest strategy(ovr) or (ova)** splits a multi-class classification into one binary classification problem per class.


**The One-vs-One(ovo)** strategy splits a multi-class classification into one binary classification problem per each pair of classes.

### The One-vs-Rest strategy(ovr) or One-vs-All(ova) 

For example, given a multi-class classification problem with examples for each class ‘red,’ ‘blue,’ and ‘green‘. This could be divided into three binary classification datasets as follows:

- Binary Classification Problem 1: red vs [blue, green]
- Binary Classification Problem 2: blue vs [red, green]
- Binary Classification Problem 3: green vs [red, blue]

A possible downside of this approach is that it requires one model to be created for each class. For example, three classes requires three models. This could be an issue for large datasets (e.g. millions of rows), slow models (e.g. neural networks), or very large numbers of classes (e.g. hundreds of classes).

This approach requires that each model predicts a class membership probability or a probability-like score. The argmax of these scores (class index with the largest score) is then used to predict a class.


### Use Logistic Regression for MultiClass classification using parameter : multi_class='ovr'

In [1]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [2]:
# Create Dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=3,n_informative=5,n_redundant=5,random_state=42)

In [3]:
#Apply the model
logcf = LogisticRegression(
    penalty='l2',
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    multi_class='ovr',  # we have to play with this setting for multiclassification using Logistic Regression
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)

In [4]:
logcf.fit(X,y)

LogisticRegression(multi_class='ovr')

In [5]:
y_pred = logcf.predict(X)

In [6]:
type(y_pred)

numpy.ndarray

In [7]:
import numpy as np
import pandas as pd

In [8]:
y_pred.shape

(1000,)

In [9]:
np.unique(y_pred,return_counts=True)

(array([0, 1, 2]), array([385, 338, 277], dtype=int64))

### Use Logistic Regression for MultiClass classification using parameter : multi_class='auto'

In [10]:
# logistic regression for multi-class classification using a one-vs-rest
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [11]:
# Create Dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=3,n_informative=5,n_redundant=5,random_state=42)

In [12]:
# Create model
logregcf = LogisticRegression(multi_class='auto')

In [13]:
logregcf.fit(X,y)

LogisticRegression()

In [14]:
y_pred_logregcf = logregcf.predict(X)

In [15]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([336, 332, 332], dtype=int64))

In [16]:
np.unique(y_pred_logregcf,return_counts=True)

(array([0, 1, 2]), array([355, 340, 305], dtype=int64))

### How to use the OneVsRestClassifier class with a LogisticRegression class used as the binary classification model.

In [17]:
# Define the classification method
from sklearn.multiclass import OneVsRestClassifier
logreg = LogisticRegression(multi_class='auto')
ovr = OneVsRestClassifier(logreg)

In [18]:
ovr.fit(X,y)

OneVsRestClassifier(estimator=LogisticRegression())

In [19]:
y_pred_ovr = ovr.predict(X)

In [20]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([336, 332, 332], dtype=int64))

In [21]:
np.unique(y_pred_ovr,return_counts=True)

(array([0, 1, 2]), array([385, 338, 277], dtype=int64))

we can see that output is same with LogisticRegression parameter : multi_class='ovr' and OneVsRestClassifier class with a LogisticRegression but when we use multi_class='auto', seems like it is performinh better.

### One-Vs-One for Multi-Class Classification

For example, consider a multi-class classification problem with four classes: ‘red,’ ‘blue,’ and ‘green,’ ‘yellow.’ This could be divided into six binary classification datasets as follows:

- Binary Classification Problem 1: red vs. blue
- Binary Classification Problem 2: red vs. green
- Binary Classification Problem 3: red vs. yellow
- Binary Classification Problem 4: blue vs. green
- Binary Classification Problem 5: blue vs. yellow
- Binary Classification Problem 6: green vs. yellow

The formula for calculating the number of binary datasets, and in turn, models, is as follows:

(NumClasses * (NumClasses – 1)) / 2

- Each binary classification model may predict one class label and the model with the most predictions or votes is predicted by the one-vs-one strategy.



In [22]:
# logistic regression for multi-class classification using a one-vs-rest
from sklearn.datasets import make_classification
from sklearn.svm import SVC

In [23]:
# Create Dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=3,n_informative=5,n_redundant=5,random_state=42)

### Use SVC for MultiClass classification using parameter : decision_function_shape='ovr'

In [24]:
svc_ovr = SVC(decision_function_shape='ovr')

In [25]:
svc_ovr.fit(X,y)

SVC()

In [26]:
y_pred_svc = svc_ovr.predict(X)

In [27]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([336, 332, 332], dtype=int64))

In [28]:
np.unique(y_pred_svc,return_counts=True)

(array([0, 1, 2]), array([335, 337, 328], dtype=int64))

### Use SVC for MultiClass classification using parameter : decision_function_shape='ovo'

In [29]:
svc_ovo = SVC(decision_function_shape='ovo')

In [30]:
svc_ovo.fit(X,y)

SVC(decision_function_shape='ovo')

In [31]:
y_pred_svc_ovo = svc_ovo.predict(X)

In [32]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([336, 332, 332], dtype=int64))

In [33]:
np.unique(y_pred_svc_ovo,return_counts=True)

(array([0, 1, 2]), array([335, 337, 328], dtype=int64))

### How to use the OneVsOneClassifier class with a SVM class used as the binary classification model.

In [34]:
from sklearn.multiclass import OneVsOneClassifier

In [35]:
svc_ovr_class_ovo = SVC(decision_function_shape='ovr')
#svc_ovr_class_ovo = SVC(decision_function_shape='ovo')

In [36]:
svc_class_ovo = OneVsOneClassifier(svc_ovr_class_ovo)

In [37]:
svc_class_ovo.fit(X,y)

OneVsOneClassifier(estimator=SVC())

In [38]:
y_pred_svc_class_ovo = svc_ovo.predict(X)

In [39]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([336, 332, 332], dtype=int64))

In [40]:
np.unique(y_pred_svc_class_ovo,return_counts=True)

(array([0, 1, 2]), array([335, 337, 328], dtype=int64))

Getting same output from each methods with SVM, it may be due to datasize is small, but it may vary with large dataset